<p>Welcome to the YourWiki Server Information Centre. Here, you'll find the absolute latest up-to-date information about the status and history of the YourWiki servers.</p>

<p>We, the systems administrators of YourWiki, keep this as a record for themselves, but we hope that it's a useful reference for some of our users, too.</p>

<h2>Useful Links</h2>
<ul>
	<li><a href="/logs">Admin. Logs</a> &mdash; View configuration changes, server updates, etc.</li>
	<li><a href="/status">Server Status</a> &mdash; See which components of YourWiki are currently functioning properly, and which aren't.</li>
</ul>
