<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta content="Boks - 0.2.3" name="generator"/>
<title>YourWiki</title>
<!-- Framework CSS -->
<link rel="stylesheet" href="/css/screen.css" type="text/css" media="screen, projection">
<link rel="stylesheet" href="/css/print.css" type="text/css" media="print">
<!--[if IE]><link rel="stylesheet" href="/css/ie.css" type="text/css" media="screen, projection"><![endif]-->

<!-- customisations -->
<link rel="stylesheet" href="/css/style.css" type="text/css" media="screen">
</head>
<body>
<div class="container">
	<div class="span-24 last" id="header">
		YourWiki MediaWiki Hosting
	</div>
	<!-- end header -->

	<div class="span-24 last" id="navigation">
		<ul>
			<li><a href="/">home</a></li>
			<li><a href="/logs">admin logs</a></li>
			<li><a href="/status">server status</a></li>
		</ul>
	</div>
	<!-- end navigation -->

	<div class="clear span-24 last" id="content">
		<?= $yield ?>
	</div>
	<!-- end content -->

	<div class="clear span-24 last" id="footer">
		Copyright &copy; YourWiki MediaWiki Hosting 2009, All Rights Reserved.
	</div>
	<!-- end footer -->
</div>
</body>
</html>